// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/testdata/sample.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sub  *HelloWorldSub `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
}

func (x *HelloWorld) Reset() {
	*x = HelloWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testdata_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld) ProtoMessage() {}

func (x *HelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld.ProtoReflect.Descriptor instead.
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return file_internal_testdata_sample_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorld) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloWorld) GetSub() *HelloWorldSub {
	if x != nil {
		return x.Sub
	}
	return nil
}

type HelloWorldSub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloWorldSub) Reset() {
	*x = HelloWorldSub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testdata_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldSub) ProtoMessage() {}

func (x *HelloWorldSub) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldSub.ProtoReflect.Descriptor instead.
func (*HelloWorldSub) Descriptor() ([]byte, []int) {
	return file_internal_testdata_sample_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorldSub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_testdata_sample_proto protoreflect.FileDescriptor

var file_internal_testdata_sample_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x0a, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x03,
	0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53,
	0x75, 0x62, 0x52, 0x03, 0x73, 0x75, 0x62, 0x22, 0x23, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6e, 0x67, 0x70,
	0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x3b,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_testdata_sample_proto_rawDescOnce sync.Once
	file_internal_testdata_sample_proto_rawDescData = file_internal_testdata_sample_proto_rawDesc
)

func file_internal_testdata_sample_proto_rawDescGZIP() []byte {
	file_internal_testdata_sample_proto_rawDescOnce.Do(func() {
		file_internal_testdata_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_testdata_sample_proto_rawDescData)
	})
	return file_internal_testdata_sample_proto_rawDescData
}

var file_internal_testdata_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testdata_sample_proto_goTypes = []interface{}{
	(*HelloWorld)(nil),    // 0: testdata.HelloWorld
	(*HelloWorldSub)(nil), // 1: testdata.HelloWorldSub
}
var file_internal_testdata_sample_proto_depIdxs = []int32{
	1, // 0: testdata.HelloWorld.sub:type_name -> testdata.HelloWorldSub
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_testdata_sample_proto_init() }
func file_internal_testdata_sample_proto_init() {
	if File_internal_testdata_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_testdata_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_testdata_sample_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldSub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_testdata_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_sample_proto_goTypes,
		DependencyIndexes: file_internal_testdata_sample_proto_depIdxs,
		MessageInfos:      file_internal_testdata_sample_proto_msgTypes,
	}.Build()
	File_internal_testdata_sample_proto = out.File
	file_internal_testdata_sample_proto_rawDesc = nil
	file_internal_testdata_sample_proto_goTypes = nil
	file_internal_testdata_sample_proto_depIdxs = nil
}
